const Info = [
  {
    id: 0,
    color: "Red",
    team: "Rm",
    city: "London",
    gender: "Male",
    merken: "merken1",
    old: 22.99,
    new: 23.49,
  },
  {
    id: 1,
    color: "Red",
    team: "Barca",
    city: "London",
    gender: "Female",
    merken: "merken2",
    old: 22.99,
    new: 16.49,
  },
  {
    id: 2,
    color: "Blue",
    team: "Barca",
    city: "Liverpool",
    gender: "Male",
    merken: "merken3",
    old: 22.99,
    new: 25.49,
  },
  {
    id: 3,
    color: "Blue",
    team: "Rm",
    city: "Manchester",
    gender: "Male",
    merken: "merken4",
    old: 22.99,
    new: 18.49,
  },
  {
    id: 4,
    color: "Yellow",
    team: "Rm",
    city: "Manchester",
    gender: "Female",
    merken: "merken5",
    old: 22.99,
    new: 19.49,
  },
  {
    id: 5,
    color: "Blue",
    team: "Barca",
    city: "Manchester",
    gender: "Male",
    merken: "merken6",
    old: 22.99,
    new: 20.49,
  },
  {
    id: 6,
    color: "Blue",
    team: "Rm",
    city: "London",
    gender: "Male",
    merken: "merken7",
    old: 22.99,
    new: 21.49,
  },
  {
    id: 7,
    color: "",
    team: "",
    city: "",
    gender: "",
  },
];
export default Info;
