const Info = [
  {
    id: 0,
    color: "Red",
    src: "/images/image0.jpg",
    team: "Rm",
    city: "London",
    gender: "Male",
    merken: "java",
    old: 22.99,
    new: 23.49,
  },
  {
    id: 1,
    color: "Red",
    src: "/images/image1.jpg",
    team: "Barca",
    city: "London",
    gender: "Female",
    merken: "python",
    old: 22.99,
    new: 16.49,
  },
  {
    id: 2,
    color: "Blue",
    src: "/images/image2.jpeg",
    team: "Barca",
    city: "Liverpool",
    gender: "Male",
    merken: "go",
    old: 22.99,
    new: 25.49,
  },
  {
    id: 3,
    color: "Blue",
    src: "/images/image3.jpg",
    team: "Rm",
    city: "Manchester",
    gender: "Male",
    merken: "katlin",
    old: 22.99,
    new: 18.49,
  },
  {
    id: 4,
    color: "Yellow",
    src: "/images/image4.jpg",
    team: "Rm",
    city: "Manchester",
    gender: "Female",
    merken: "ruby",
    old: 22.99,
    new: 19.49,
  },
  {
    id: 5,
    color: "Blue",
    src: "/images/image5.jpg",
    team: "Barca",
    city: "Manchester",
    gender: "Male",
    merken: "django",
    old: 22.99,
    new: 20.49,
  },
  {
    id: 6,
    color: "Blue",
    src: "/images/image6.jpg",
    team: "Rm",
    city: "London",
    gender: "Male",
    merken: "react",
    old: 22.99,
    new: 21.49,
  },
  {
    id: 7,
    color: "",
    team: "",
    city: "",
    gender: "",
  },
];
export default Info;
